-- Sprint 03A — 015: Admin Email Setting Slot
--
-- Celebrate follows a single-admin operational model. The admin_email
-- app_settings key is read by Sprint 04 auth middleware (server-side only).
--
-- The real admin email must NEVER be committed to version control or exposed
-- to the frontend. Set it in .env.local (gitignored):
--   ADMIN_EMAIL=your-real-admin@email.com
--
-- Sprint 04 bootstrap will upsert app_settings.admin_email from that env var.
-- Production databases already seeded manually retain their existing value.

-- Intentionally no INSERT: email is deploy-time configuration, not migration data.
